<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('categories')->insert([
            ///////////////////////////////////////////  Maincate TH  //////////////////////////////////////////////////////////////
            [

                'id' => 1,
                'cate_url' => '/',
                'cate_name' => 'หน้าแรก',
                'cate_title' => 'หน้าแรก',
                'cate_keyword' => 'หน้าแรก',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_topside' => true,
                'is_leftside' => false,
                'is_bottomside' => false,
                'is_main_page' => true,
                'cate_position' => 1,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 1,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => true,
            ],
            [

                'id' => 2,
                'cate_url' => 'product',
                'cate_name' => 'สินค้า',
                'cate_title' => 'สินค้า',
                'cate_keyword' => 'สินค้า',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_topside' => true,
                'is_leftside' => false,
                'is_bottomside' => false,
                'is_main_page' => true,
                'cate_position' => 1,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 2,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => true,
            ],
            [

                'id' => 3,
                'cate_url' => 'service',
                'cate_name' => 'บริการ',
                'cate_title' => 'บริการ',
                'cate_keyword' => 'บริการ',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_topside' => true,
                'is_leftside' => false,
                'is_bottomside' => false,
                'is_main_page' => true,
                'cate_position' => 1,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 3,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => true,
            ],
            [

                'id' => 4,
                'cate_url' => 'reviews',
                'cate_name' => 'รีวิวสินค้า',
                'cate_title' => 'รีวิวสินค้า',
                'cate_keyword' => 'รีวิวสินค้า',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_topside' => true,
                'is_leftside' => false,
                'is_bottomside' => false,
                'is_main_page' => true,
                'cate_position' => 1,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 4,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => true,
            ],
            [

                'id' => 5,
                'cate_url' => 'how-to-buy',
                'cate_name' => 'วิธีการสั่งซื้อ',
                'cate_title' => 'วิธีการสั่งซื้อ',
                'cate_keyword' => 'วิธีการสั่งซื้อ',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_topside' => true,
                'is_leftside' => false,
                'is_bottomside' => false,
                'is_main_page' => true,
                'cate_position' => 1,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 5,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => true,
            ],
            [
                'id' => 6,
                'cate_url' => 'contact',
                'cate_name' => 'ติดต่อเรา',
                'cate_title' => 'ติดต่อเรา',
                'cate_keyword' => 'ติดต่อเรา',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_topside' => true,
                'is_leftside' => false,
                'is_bottomside' => false,
                'is_main_page' => true,
                'cate_position' => 1,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 6,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => true,
            ],
            [
                'id' => 7,
                'cate_url' => 'About us',
                'cate_name' => 'เกี่ยวกับเรา',
                'cate_title' => 'เกี่ยวกับเรา',
                'cate_keyword' => 'เกี่ยวกับเรา',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_topside' => true,
                'is_leftside' => false,
                'is_bottomside' => false,
                'is_main_page' => true,
                'cate_position' => 1,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 6,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => true,
            ],
            [
                'id' => 8,
                'cate_url' => 'BLANKGUN',
                'cate_name' => '',
                'cate_title' => 'ปืนเเบลงค์กัน bLANKGUN',
                'cate_keyword' => 'BLANKGUN',
                'cate_description' => 'ปืนเเบลงค์กัน',
                'cate_redirect' => '',
                'is_menu' => false,
                'is_topside' => false,
                'is_leftside' => true,
                'is_bottomside' => false,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 1,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => true,
            ],
            [
                'id' => 9,
                'cate_url' => 'BLANKGUN/RETAY',
                'cate_name' => '',
                'cate_title' => 'RETAY',
                'cate_keyword' => 'BLANKGUN',
                'cate_description' => 'ปืนเเบลงค์กัน',
                'cate_redirect' => '',
                'is_menu' => false,
                'is_topside' => false,
                'is_leftside' => false,
                'is_bottomside' => false,
                'is_main_page' => false,
                'cate_position' => 2,
                'cate_parent_id' => 8,
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 2,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => true,
            ],
            [
                'id' => 10,
                'cate_url' => 'ปืนสั้นเเก๊ส',
                'cate_name' => '',
                'cate_title' => 'ปืนสั้นเเก๊ส',
                'cate_keyword' => 'ปืนสั้นเเก๊ส',
                'cate_description' => 'ปืนเเบลงค์กัน',
                'cate_redirect' => '',
                'is_menu' => false,
                'is_topside' => false,
                'is_leftside' => true,
                'is_bottomside' => false,
                'is_main_page' => false,
                'cate_position' => 2,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 2,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => true,
            ],
            [
                'id' => 11,
                'cate_url' => 'BLANKGUN/Sur',
                'cate_name' => '',
                'cate_title' => 'Sur',
                'cate_keyword' => 'Sur',
                'cate_description' => 'Sur',
                'cate_redirect' => '',
                'is_menu' => false,
                'is_topside' => false,
                'is_leftside' => false,
                'is_bottomside' => false,
                'is_main_page' => false,
                'cate_position' => 3,
                'cate_parent_id' => 8,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 3,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => true,
            ],
            [
                'id' => 12,
                'cate_url' => 'ปืนยาวไฟฟ้า',
                'cate_name' => '',
                'cate_title' => 'ปืนยาวไฟฟ้า',
                'cate_keyword' => 'ปืนยาวไฟฟ้า',
                'cate_description' => 'ปืนยาวไฟฟ้า',
                'cate_redirect' => '',
                'is_menu' => false,
                'is_topside' => false,
                'is_leftside' => true,
                'is_bottomside' => false,
                'is_main_page' => false,
                'cate_position' => 3,
                'cate_parent_id' => 0,
                'cate_level' => 0,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 3,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => true,
            ],
            ///////////////////////////////////////////  Subcate TH  //////////////////////////////////////////////////////////////
            /*   [

                'id' => 7, //ภาควิชา
                'cate_url' => 'account/history', //ภาควิชา
                'cate_name' => 'ประวัติความเป็นมา',
                'cate_title' => 'ประวัติความเป็นมา',
                'cate_keyword' => 'ประวัติความเป็นมา',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_topside' => true,
                'is_leftside' => true,
                'is_bottomside' => false,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 2,
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 7,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => false,
            ],
            [

                'id' => 8, //ภาควิชา
                'cate_url' => 'department/vision', //ภาควิชา
                'cate_name' => 'โครงสร้าง วิสัยทัศน์ พันธกิจ',
                'cate_title' => 'โครงสร้าง วิสัยทัศน์ พันธกิจ',
                'cate_keyword' => 'โครงสร้าง วิสัยทัศน์ พันธกิจ',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_topside' => true,
                'is_leftside' => true,
                'is_bottomside' => false,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 2,
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 8,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => false,
            ],
            [

                'id' => 9, //ภาควิชา
                'cate_url' => 'department/employee', //ภาควิชา
                'cate_name' => 'บุคลากรสายวิชาการ',
                'cate_title' => 'บุคลากรสายวิชาการ',
                'cate_keyword' => 'บุคลากรสายวิชาการ',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_topside' => true,
                'is_leftside' => true,
                'is_bottomside' => false,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 2,
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 9,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => false,
            ],

            [

                'id' => 10, //การเรียนการสอน
                'cate_url' => 'education/doctor', //การเรียนการสอน
                'cate_name' => 'หลักสูตรแพทยศาสตรบัณฑิต',
                'cate_title' => 'หลักสูตรแพทยศาสตรบัณฑิต',
                'cate_keyword' => 'หลักสูตรแพทยศาสตรบัณฑิต',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_topside' => true,
                'is_leftside' => true,
                'is_bottomside' => false,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 3,
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 10,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => false,
            ],
            [

                'id' => 11, //การเรียนการสอน
                'cate_url' => 'education/resident', //การเรียนการสอน
                'cate_name' => 'หลักสูตรแพทย์ประจำบ้าน',
                'cate_title' => 'หลักสูตรแพทย์ประจำบ้าน',
                'cate_keyword' => 'หลักสูตรแพทย์ประจำบ้าน',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_topside' => true,
                'is_leftside' => true,
                'is_bottomside' => false,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 3,
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 11,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => false,
            ],
            [

                'id' => 12, //การบริการเวชศาสตร์ฟื้นฟู
                'cate_url' => 'service/schedule', //การบริการเวชศาสตร์ฟื้นฟู
                'cate_name' => 'ตารางออกตรวจ',
                'cate_title' => 'ตารางออกตรวจ',
                'cate_keyword' => 'ตารางออกตรวจ',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_topside' => true,
                'is_leftside' => true,
                'is_bottomside' => false,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 4,
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 12,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => false,
            ],
            [

                'id' => 13, //การบริการเวชศาสตร์ฟื้นฟู
                'cate_url' => 'service/scope', //การบริการเวชศาสตร์ฟื้นฟู
                'cate_name' => 'ขอบเขตการให้บริการ',
                'cate_title' => 'ขอบเขตการให้บริการ',
                'cate_keyword' => 'ขอบเขตการให้บริการ',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_topside' => true,
                'is_leftside' => true,
                'is_bottomside' => false,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 4,
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 13,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => false,
            ],
            [

                'id' => 14, //งานวิจัยนวัตกรรม
                'cate_url' => 'researchall', //งานวิจัยนวัตกรรม
                'cate_name' => 'งานวิจัย',
                'cate_title' => 'งานวิจัย',
                'cate_keyword' => 'งานวิจัย',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_topside' => true,
                'is_leftside' => true,
                'is_bottomside' => false,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 5,
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 14,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => true,
            ],
            [

                'id' => 15,
                'cate_url' => 'research/article',
                'cate_name' => 'บทความ',
                'cate_title' => 'บทความ',
                'cate_keyword' => 'บทความ',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_topside' => true,
                'is_leftside' => true,
                'is_bottomside' => false,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 5,
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 15,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => true,
            ],
            [

                'id' => 16, //งานวิจัยนวัตกรรม
                'cate_url' => 'research/book', //งานวิจัยนวัตกรรม
                'cate_name' => 'หนังสือตำรา',
                'cate_title' => 'หนังสือตำรา',
                'cate_keyword' => 'หนังสือตำรา',
                'cate_description' => '',
                'cate_redirect' => '',
                'is_menu' => true,
                'is_topside' => true,
                'is_leftside' => true,
                'is_bottomside' => false,
                'is_main_page' => false,
                'cate_position' => 1,
                'cate_parent_id' => 5,
                'cate_level' => 1,
                'language' => 'th',
                'defaults' => true,
                'cate_priority' => 16,
                'cate_thumbnail' => '',
                'cate_thumbnail_title' => '',
                'cate_thumbnail_alt' => '',
                'cate_h1' => '',
                'cate_h2' => '',
                'meta_title' => '',
                'meta_description' => '',
                'meta_keyword' => '',
                'cate_status_display' => false,
            ]*/
        ]);
    }
}
