<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('categories')->insert([
            ///////////////////////////////////////////  Maincate TH  //////////////////////////////////////////////////////////////
            [
                'id' => 1,
                'cate_title' => 'Home',
                'cate_keyword' => 'Home',
                'cate_url' => NULL,
                'cate_redirect' => "/ar",
                'cate_parent_id' => 0,
                'cate_root_id' => 1,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 1,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'ar',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 1,
                'cate_title' => 'Home',
                'cate_keyword' => 'Home',
                'cate_url' => NULL,
                'cate_redirect' => "/en",
                'cate_parent_id' => 0,
                'cate_root_id' => 1,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 1,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'en',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 1,
                'cate_title' => 'หน้าหลัก',
                'cate_keyword' => 'Home',
                'cate_url' => NULL,
                'cate_redirect' => "/th",
                'cate_parent_id' => 0,
                'cate_root_id' => 1,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 1,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'th',
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 2,
                'cate_title' => 'VISION',
                'cate_keyword' => 'VISION',
                'cate_url' => '/vision',
                'cate_redirect' => "/ar/vision",
                'cate_parent_id' => 0,
                'cate_root_id' => 2,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 2,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'ar',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 2,
                'cate_title' => 'VISION',
                'cate_keyword' => 'VISION',
                'cate_url' => '/vision',
                'cate_redirect' => "/en/vision",
                'cate_parent_id' => 0,
                'cate_root_id' => 2,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 2,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'en',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 2,
                'cate_title' => 'วิสัยทัศน์',
                'cate_keyword' => 'VISION',
                'cate_url' => '/vision',
                'cate_redirect' => "/th/vision",
                'cate_parent_id' => 0,
                'cate_root_id' => 2,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 2,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'th',
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 3,
                'cate_title' => 'PRODUCT',
                'cate_keyword' => 'PRODUCT',
                'cate_url' => '/product',
                'cate_redirect' => "/ar/product",
                'cate_parent_id' => 0,
                'cate_root_id' => 3,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 4,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'ar',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 3,
                'cate_title' => 'PRODUCT',
                'cate_keyword' => 'PRODUCT',
                'cate_url' => '/product',
                'cate_redirect' => "/en/product",
                'cate_parent_id' => 0,
                'cate_root_id' => 3,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 4,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'en',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 3,
                'cate_title' => 'ผลิตภัณฑ์',
                'cate_keyword' => 'PRODUCT',
                'cate_url' => '/product',
                'cate_redirect' => "/th/product",
                'cate_parent_id' => 0,
                'cate_root_id' => 3,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 4,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'th',
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 4,
                'cate_title' => 'News',
                'cate_keyword' => 'NEWS',
                'cate_url' => '/news',
                'cate_redirect' => "/ar/news",
                'cate_parent_id' => 0,
                'cate_root_id' => 4,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 3,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'ar',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 4,
                'cate_title' => 'News',
                'cate_keyword' => 'NEWS',
                'cate_url' => '/news',
                'cate_redirect' => "/en/news",
                'cate_parent_id' => 0,
                'cate_root_id' => 4,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 3,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'en',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 4,
                'cate_title' => 'ข่าว',
                'cate_keyword' => 'NEWS',
                'cate_url' => '/news',
                'cate_redirect' => "/th/news",
                'cate_parent_id' => 0,
                'cate_root_id' => 4,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 3,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'th',
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 5,
                'cate_title' => 'TERM&CONDITION',
                'cate_keyword' => 'TERM&CONDITION',
                'cate_url' => '/term',
                'cate_redirect' => "/ar/term",
                'cate_parent_id' => 0,
                'cate_root_id' => 5,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 5,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'ar',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 5,
                'cate_title' => 'TERM&CONDITION',
                'cate_keyword' => 'TERM&CONDITION',
                'cate_url' => '/term',
                'cate_redirect' => "/en/term",
                'cate_parent_id' => 0,
                'cate_root_id' => 5,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 5,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'en',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 5,
                'cate_title' => 'ข้อกำหนด/เงื่อนไข',
                'cate_keyword' => 'TERM&CONDITION',
                'cate_url' => '/term',
                'cate_redirect' => "/th/term",
                'cate_parent_id' => 0,
                'cate_root_id' => 5,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 5,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'th',
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 6,
                'cate_title' => 'تسجيل دخول',
                'cate_keyword' => 'CONTACT US',
                'cate_url' => '/contact',
                'cate_redirect' => "/ar/contact",
                'cate_parent_id' => 0,
                'cate_root_id' => 6,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 6,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'ar',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 6,
                'cate_title' => 'CONTACT US',
                'cate_keyword' => 'CONTACT US',
                'cate_url' => '/contact',
                'cate_redirect' => "/en/contact",
                'cate_parent_id' => 0,
                'cate_root_id' => 6,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 6,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'en',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 6,
                'cate_title' => 'ติดต่อเรา',
                'cate_keyword' => 'CONTACT US',
                'cate_url' => '/contact',
                'cate_redirect' => "/th/contact",
                'cate_parent_id' => 0,
                'cate_root_id' => 6,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 6,
                'cate_position' => 1,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'th',
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 7,
                'cate_title' => 'MEMBER',
                'cate_keyword' => 'MEMBER',
                'cate_url' => 'member',
                'cate_redirect' => NULL,
                'cate_parent_id' => 0,
                'cate_root_id' => 7,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 7,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'ar',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
             [
                'id' => 7,
                'cate_title' => 'MEMBER',
                'cate_keyword' => 'MEMBER',
                'cate_url' => 'member',
                'cate_redirect' => NULL,
                'cate_parent_id' => 0,
                'cate_root_id' => 7,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 7,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'en',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
             [
                'id' => 7,
                'cate_title' => 'สมาชิก',
                'cate_keyword' => 'MEMBER',
                'cate_url' => 'member',
                'cate_redirect' => NULL,
                'cate_parent_id' => 0,
                'cate_root_id' => 7,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 7,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'th',
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 8,
                'cate_title' => 'Register',
                'cate_keyword' => 'REGISTER',
                'cate_url' => 'register',
                'cate_redirect' => NULL,
                'cate_parent_id' => 0,
                'cate_root_id' => 8,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 8,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'ar',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 8,
                'cate_title' => 'Register',
                'cate_keyword' => 'REGISTER',
                'cate_url' => 'register',
                'cate_redirect' => NULL,
                'cate_parent_id' => 0,
                'cate_root_id' => 8,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 8,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'en',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 8,
                'cate_title' => 'ลงทะเบียน',
                'cate_keyword' => 'REGISTER',
                'cate_url' => 'register',
                'cate_redirect' => NULL,
                'cate_parent_id' => 0,
                'cate_root_id' => 8,
                'cate_level' => 0,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 8,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 1,
                'is_product_cate' => 0,
                'language' => 'th',
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 9,
                'cate_title' => 'SignIn',
                'cate_keyword' => 'Sign In',
                'cate_url' => 'register/sign in',
                'cate_redirect' => '/ar/login',
                'cate_parent_id' => 8,
                'cate_root_id' => 8,
                'cate_level' => 1,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 9,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 0,
                'is_product_cate' => 0,
                'language' => 'ar',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 9,
                'cate_title' => 'SignIn',
                'cate_keyword' => 'Sign In',
                'cate_url' => 'register/sign in',
                'cate_redirect' => '/en/login',
                'cate_parent_id' => 8,
                'cate_root_id' => 8,
                'cate_level' => 1,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 9,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 0,
                'is_product_cate' => 0,
                'language' => 'en',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 9,
                'cate_title' => 'เข้าสู่ระบบ',
                'cate_keyword' => 'Sign In',
                'cate_url' => 'register/sign in',
                'cate_redirect' => '/th/login',
                'cate_parent_id' => 8,
                'cate_root_id' => 8,
                'cate_level' => 1,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 9,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 0,
                'is_product_cate' => 0,
                'language' => 'th',
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 12,
                'cate_title' => 'Register',
                'cate_keyword' => 'Register',
                'cate_url' => 'register/register',
                'cate_redirect' => '/ar/register',
                'cate_parent_id' => 8,
                'cate_root_id' => 8,
                'cate_level' => 1,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 10,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 0,
                'is_product_cate' => 0,
                'language' => 'ar',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 12,
                'cate_title' => 'Register',
                'cate_keyword' => 'Register',
                'cate_url' => 'register/register',
                'cate_redirect' => '/en/register',
                'cate_parent_id' => 8,
                'cate_root_id' => 8,
                'cate_level' => 1,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 10,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 0,
                'is_product_cate' => 0,
                'language' => 'en',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 12,
                'cate_title' => 'ลงทะเบียน',
                'cate_keyword' => 'Register',
                'cate_url' => 'register/register',
                'cate_redirect' => '/th/register',
                'cate_parent_id' => 8,
                'cate_root_id' => 8,
                'cate_level' => 1,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 10,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 0,
                'is_product_cate' => 0,
                'language' => 'th',
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 13,
                'cate_title' => 'Profile',
                'cate_keyword' => 'Profile',
                'cate_url' => 'member/Profile',
                'cate_redirect' => 'ar/profile',
                'cate_parent_id' => 7,
                'cate_root_id' => 7,
                'cate_level' => 1,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 11,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 0,
                'is_product_cate' => 0,
                'language' => 'ar',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 13,
                'cate_title' => 'Profile',
                'cate_keyword' => 'Profile',
                'cate_url' => 'member/Profile',
                'cate_redirect' => 'en/profile',
                'cate_parent_id' => 7,
                'cate_root_id' => 7,
                'cate_level' => 1,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 11,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 0,
                'is_product_cate' => 0,
                'language' => 'en',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 13,
                'cate_title' => 'โปรไฟล์',
                'cate_keyword' => 'Profile',
                'cate_url' => 'member/Profile',
                'cate_redirect' => 'th/profile',
                'cate_parent_id' => 7,
                'cate_root_id' => 7,
                'cate_level' => 1,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 11,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 0,
                'is_product_cate' => 0,
                'language' => 'th',
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 14,
                'cate_title' => 'Sign Out',
                'cate_keyword' => 'Sign out',
                'cate_url' => 'member/sign out',
                'cate_redirect' => 'ar/logout',
                'cate_parent_id' => 7,
                'cate_root_id' => 7,
                'cate_level' => 1,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 12,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 0,
                'is_product_cate' => 0,
                'language' => 'ar',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 14,
                'cate_title' => 'Sign Out',
                'cate_keyword' => 'Sign out',
                'cate_url' => 'member/sign out',
                'cate_redirect' => 'en/logout',
                'cate_parent_id' => 7,
                'cate_root_id' => 7,
                'cate_level' => 1,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 12,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 0,
                'is_product_cate' => 0,
                'language' => 'en',
                'defaults' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 14,
                'cate_title' => 'ออกจากระบบ',
                'cate_keyword' => 'Sign out',
                'cate_url' => 'member/sign out',
                'cate_redirect' => 'th/logout',
                'cate_parent_id' => 7,
                'cate_root_id' => 7,
                'cate_level' => 1,
                'cate_status_display' => 1,
                'is_menu' => 1,
                'is_topside' => 1,
                'is_leftside' => 0,
                'is_rightside' => 0,
                'is_bottomside' => 0,
                'cate_priority' => 12,
                'cate_position' => 2,
                'on_product' => 0,
                'is_main_page' => 0,
                'is_product_cate' => 0,
                'language' => 'th',
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ]
        ]);
    }
}
