<?php

namespace Database\Seeders;


use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class LanguageConfigsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('language_configs')->insert([
            [
                'id' => 1,
                'param' => 'Register_User name',
                'title' => '*ชื่อผู้ใช้',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'param' => 'Register_User name',
                'title' => '*User name',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'param' => 'Register_User name',
                'title' => '*اسم المستخدم',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'param' => 'Register_First Name',
                'title' => '*ชื่อ',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'param' => 'Register_First Name',
                'title' => '*First Name',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'param' => 'Register_First Name',
                'title' => '*اسم',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'param' => 'Register_Last Name',
                'title' => '*นามสกุล',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'param' => 'Register_Last Name',
                'title' => '*Last Name',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 9,
                'param' => 'Register_Last Name',
                'title' => '*اسم العائلة',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10,
                'param' => 'Register_Telephone Number',
                'title' => '*เบอร์โทรศัพท์',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 11,
                'param' => 'Register_Telephone Number',
                'title' => '*Telephone Number',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 12,
                'param' => 'Register_Telephone Number',
                'title' => '*رقم الهاتف',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 13,
                'param' => 'Register_Email',
                'title' => '*อีเมล',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 14,
                'param' => 'Register_Email',
                'title' => '*Email',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 15,
                'param' => 'Register_Email',
                'title' => '*بريد إلكتروني',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 16,
                'param' => 'Register_Password',
                'title' => '*รหัสผ่าน',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 17,
                'param' => 'Register_Password',
                'title' => '*Password',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 18,
                'param' => 'Register_Password',
                'title' => '*كلمة المرور',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 19,
                'param' => 'Register_Confirm Password',
                'title' => '*ยืนยันรหัสผ่าน',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 20,
                'param' => 'Register_Confirm Password',
                'title' => '*Confirm Password',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 21,
                'param' => 'Register_Confirm Password',
                'title' => '*تأكيد كلمة المرور',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 22,
                'param' => 'Register_information',
                'title' => 'ข้อมูล',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 23,
                'param' => 'Register_information',
                'title' => 'INFORMATION',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 24,
                'param' => 'Register_information',
                'title' => 'استعلامات',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 25,
                'param' => 'Register_Text_Heading3',
                'title' => 'คุณทำอาชีพอะไร?',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 26,
                'param' => 'Register_Text_Heading3',
                'title' => 'What is your occupation?',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 27,
                'param' => 'Register_Text_Heading3',
                'title' => 'ما هي مهنتك؟',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 28,
                'param' => 'Register_Text_Heading4',
                'title' => 'คุณมาจากประเทศไหน?',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 29,
                'param' => 'Register_Text_Heading4',
                'title' => 'Which country are you from?',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 30,
                'param' => 'Register_Text_Heading4',
                'title' => 'من أي بلد أنت؟',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 31,
                'param' => 'Register_Text_Heading1',
                'title' => 'ลงทะเบียนเพื่อรับรหัสผ่านเพื่อการเติบโตทางธุรกิจร่วมกัน (B2B)',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 32,
                'param' => 'Register_Text_Heading1',
                'title' => 'Register To Get Password For Business Growth Together (B2B)',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 33,
                'param' => 'Register_Text_Heading1',
                'title' => 'سجل للحصول على كلمة مرور لنمو الأعمال معًا (B2B)',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 34,
                'param' => 'Register_Text_Heading2',
                'title' => 'กรุณากรอกข้อมูลให้ครบถ้วนเพื่อสมัครสมาชิก',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 35,
                'param' => 'Register_Text_Heading2',
                'title' => 'Please fill out the information completely to get member.',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 36,
                'param' => 'Register_Text_Heading2',
                'title' => 'يرجى ملء المعلومات كاملة للحصول على العضوية.',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 37,
                'param' => 'Register_Text_Heading5',
                'title' => '\"ข้อมูลส่วนบุคคลของคุณมีความสำคัญต่อเรา เราต้องการข้อมูลของคุณเพื่อการประมวลผลและปรับปรุงบริการของเราเท่านั้น โปรดให้ความยินยอม หากคุณยินยอม ถือว่าคุณยอมรับข้อกำหนดการใช้งานตามระเบียบ PDPA ของประเทศไทย โปรดอ่านข้อกำหนดในนโยบายความเป็นส่วนตัวของเรา\"',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 38,
                'param' => 'Register_Text_Heading5',
                'title' => '\"Your personal information is important to us. We need your information solely for processing and improving the services we provide. Please give your consent. If you agree, you accept the terms of use in accordance with Thailand\'s PDPA regulations. Read the terms of our privacy policy.\"',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 39,
                'param' => 'Register_Text_Heading5',
                'title' => '\"معلوماتك الشخصية مهمة بالنسبة لنا. نحتاجها فقط لمعالجة وتحسين الخدمات التي نقدمها. يُرجى الموافقة. بموافقتك، فإنك تقبل شروط الاستخدام وفقًا للوائح قانون حماية البيانات الشخصية في تايلاند. اقرأ شروط سياسة الخصوصية الخاصة بنا.\"',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 40,
                'param' => 'Register_Select_Country',
                'title' => 'กรุณาเลือกประเทศ',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 41,
                'param' => 'Register_Select_Country',
                'title' => 'Please select a country',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 42,
                'param' => 'Register_Select_Country',
                'title' => 'الرجاء اختيار البلد',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 43,
                'param' => 'Register_Text_ACCEPT',
                'title' => 'ยอมรับ',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 44,
                'param' => 'Register_Text_ACCEPT',
                'title' => 'ACCEPT',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 45,
                'param' => 'Register_Text_ACCEPT',
                'title' => 'يقبل',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 46,
                'param' => 'Register_Text_REJECT',
                'title' => 'ปฏิเสธ',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 47,
                'param' => 'Register_Text_REJECT',
                'title' => 'REJECT',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 48,
                'param' => 'Register_Text_REJECT',
                'title' => 'يرفض',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 49,
                'param' => 'SignIn_Text_Heading1',
                'title' => 'ป้อนรหัสผ่านและเลือกผลิตภัณฑ์สำหรับตลาดของคุณ',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 50,
                'param' => 'SignIn_Text_Heading1',
                'title' => 'Key in password and selecting product for your market',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 51,
                'param' => 'SignIn_Text_Heading1',
                'title' => 'أدخل كلمة المرور واختر المنتج المناسب لسوقك',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 52,
                'param' => 'SignIn_Text_Heading2',
                'title' => 'กรุณากรอกรายละเอียดของคุณ',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 53,
                'param' => 'SignIn_Text_Heading2',
                'title' => 'Please enter your details.',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 54,
                'param' => 'SignIn_Text_Heading2',
                'title' => 'الرجاء إدخال بياناتك.',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 55,
                'param' => 'SignIn_User name',
                'title' => '*ชื่อผู้ใช้',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 56,
                'param' => 'SignIn_User name',
                'title' => '*User name',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 57,
                'param' => 'SignIn_User name',
                'title' => '*اسم المستخدم',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 58,
                'param' => 'SignIn_Password',
                'title' => '*รหัสผ่าน',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 59,
                'param' => 'SignIn_Password',
                'title' => '*Password',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 60,
                'param' => 'SignIn_Password',
                'title' => '*كلمة المرور',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 61,
                'param' => 'SignIn_RememberMe',
                'title' => 'คงอยู่ในระบบ',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 62,
                'param' => 'SignIn_RememberMe',
                'title' => 'Remember Me',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 63,
                'param' => 'SignIn_RememberMe',
                'title' => 'تذكرنى',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 64,
                'param' => 'SignIn_Forgot',
                'title' => 'ลืมรหัสผ่าน?',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 65,
                'param' => 'SignIn_Forgot',
                'title' => 'Forgot password?',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 66,
                'param' => 'SignIn_Forgot',
                'title' => 'هل نسيت كلمة السر؟',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 67,
                'param' => 'SignIn_Register',
                'title' => 'ลงทะเบียนเพื่อรับรหัสผ่านเพื่อการเติบโตทางธุรกิจร่วมกัน (B2B)',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 67,
                'param' => 'SignIn_Register',
                'title' => 'ลงทะเบียนเพื่อรับรหัสผ่านเพื่อการเติบโตทางธุรกิจร่วมกัน (B2B)',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 68,
                'param' => 'SignIn_Register',
                'title' => 'Register to get password for business growth together (B2B)',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 69,
                'param' => 'SignIn_Register',
                'title' => 'سجل للحصول على كلمة المرور لنمو الأعمال معًا (B2B)',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 70,
                'param' => 'SignIn_SIGN',
                'title' => 'เข้าสู่ระบบ',
                'language' => 'th',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 71,
                'param' => 'SignIn_SIGN',
                'title' => 'SIGN IN',
                'language' => 'en',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 72,
                'param' => 'SignIn_SIGN',
                'title' => 'تسجيل الدخول',
                'language' => 'ar',
                'page_control' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 73,
                'param' => 'Profile_MEMBER',
                'title' => 'โปรไฟล์ สมาชิก',
                'language' => 'th',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 74,
                'param' => 'Profile_MEMBER',
                'title' => 'PROFILE MEMBER',
                'language' => 'en',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 75,
                'param' => 'Profile_MEMBER',
                'title' => 'الملف الشخصي للعضو',
                'language' => 'ar',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 76,
                'param' => 'Profile_UserName',
                'title' => '*ชื่อผู้ใช้',
                'language' => 'th',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 77,
                'param' => 'Profile_UserName',
                'title' => '*User name',
                'language' => 'en',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 78,
                'param' => 'Profile_UserName',
                'title' => '*اسم المستخدم',
                'language' => 'ar',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 79,
                'param' => 'Profile_FirstName',
                'title' => '*ชื่อ',
                'language' => 'th',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 80,
                'param' => 'Profile_FirstName',
                'title' => '*First Name',
                'language' => 'en',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 81,
                'param' => 'Profile_FirstName',
                'title' => '*الاسم الأول',
                'language' => 'ar',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 82,
                'param' => 'Profile_LastName',
                'title' => '*นามสกุล',
                'language' => 'th',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 83,
                'param' => 'Profile_LastName',
                'title' => '*Last Name',
                'language' => 'en',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 84,
                'param' => 'Profile_LastName',
                'title' => '*اسم العائلة',
                'language' => 'ar',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 85,
                'param' => 'Profile_Telephone',
                'title' => '*หมายเลขโทรศัพท์',
                'language' => 'th',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 86,
                'param' => 'Profile_Telephone',
                'title' => '*Telephone Number',
                'language' => 'en',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 87,
                'param' => 'Profile_Telephone',
                'title' => '*رقم الهاتف',
                'language' => 'ar',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 88,
                'param' => 'Profile_Email',
                'title' => '*อีเมล',
                'language' => 'th',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 89,
                'param' => 'Profile_Email',
                'title' => '*Email',
                'language' => 'en',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 90,
                'param' => 'Profile_Email',
                'title' => '*بريد إلكتروني',
                'language' => 'ar',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 91,
                'param' => 'Profile_Password',
                'title' => '*รหัสผ่าน',
                'language' => 'th',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 92,
                'param' => 'Profile_Password',
                'title' => '*Password',
                'language' => 'en',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 93,
                'param' => 'Profile_Password',
                'title' => '*كلمة المرور',
                'language' => 'ar',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 94,
                'param' => 'Profile_ConfirmPassword',
                'title' => '*ยืนยันรหัสผ่าน',
                'language' => 'th',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 95,
                'param' => 'Profile_ConfirmPassword',
                'title' => '*Confirm Password',
                'language' => 'en',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 96,
                'param' => 'Profile_ConfirmPassword',
                'title' => '*تأكيد كلمة المرور',
                'language' => 'ar',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 97,
                'param' => 'Profile_SAVE',
                'title' => 'บันทึก',
                'language' => 'th',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 98,
                'param' => 'Profile_SAVE',
                'title' => 'SAVE',
                'language' => 'en',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 99,
                'param' => 'Profile_SAVE',
                'title' => 'يحفظ',
                'language' => 'ar',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 100,
                'param' => 'Profile_CANCEL',
                'title' => 'ยกเลิก',
                'language' => 'th',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 101,
                'param' => 'Profile_CANCEL',
                'title' => 'CANCEL',
                'language' => 'en',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 102,
                'param' => 'Profile_CANCEL',
                'title' => 'يلغي',
                'language' => 'ar',
                'page_control' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 103,
                'param' => 'Contact_Text_Heading1',
                'title' => 'ติดต่อเรา',
                'language' => 'th',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 104,
                'param' => 'Contact_Text_Heading1',
                'title' => 'CONTACT US',
                'language' => 'en',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 105,
                'param' => 'Contact_Text_Heading1',
                'title' => 'اتصل بنا',
                'language' => 'ar',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 106,
                'param' => 'Contact_Text_Phone',
                'title' => 'โทรศัพท์',
                'language' => 'th',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 107,
                'param' => 'Contact_Text_Phone',
                'title' => 'Phone',
                'language' => 'en',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 108,
                'param' => 'Contact_Text_Phone',
                'title' => 'هاتف',
                'language' => 'ar',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 109,
                'param' => 'Contact_Text_Website',
                'title' => 'เว็บไซต์',
                'language' => 'th',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 110,
                'param' => 'Contact_Text_Website',
                'title' => 'Website',
                'language' => 'en',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 111,
                'param' => 'Contact_Text_Website',
                'title' => 'موقع إلكتروني',
                'language' => 'ar',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 112,
                'param' => 'Contact_Text_Email',
                'title' => 'อีเมล',
                'language' => 'th',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 113,
                'param' => 'Contact_Text_Email',
                'title' => 'Email',
                'language' => 'en',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 114,
                'param' => 'Contact_Text_Email',
                'title' => 'بريد إلكتروني',
                'language' => 'ar',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 115,
                'param' => 'Contact_Text_Address',
                'title' => 'ที่อยู่',
                'language' => 'th',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 116,
                'param' => 'Contact_Text_Address',
                'title' => 'Address',
                'language' => 'en',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 117,
                'param' => 'Contact_Text_Address',
                'title' => 'عنوان',
                'language' => 'ar',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 118,
                'param' => 'Contact_Text_Heading2',
                'title' => 'บอกเราข้อความของคุณ',
                'language' => 'th',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 119,
                'param' => 'Contact_Text_Heading2',
                'title' => 'Tell Us Your Message',
                'language' => 'en',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 120,
                'param' => 'Contact_Text_Heading2',
                'title' => 'أخبرنا برسالتك',
                'language' => 'ar',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 121,
                'param' => 'Contact_Title_Name',
                'title' => 'ชื่อ:',
                'language' => 'th',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 122,
                'param' => 'Contact_Title_Name',
                'title' => 'Name:',
                'language' => 'en',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 123,
                'param' => 'Contact_Title_Name',
                'title' => 'اسم:',
                'language' => 'ar',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 124,
                'param' => 'Contact_Title_Email',
                'title' => 'อีเมล:',
                'language' => 'th',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 125,
                'param' => 'Contact_Title_Email',
                'title' => 'Email:',
                'language' => 'en',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 126,
                'param' => 'Contact_Title_Email',
                'title' => 'بريد إلكتروني:',
                'language' => 'ar',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 127,
                'param' => 'Contact_Title_Phone',
                'title' => 'โทรศัพท์:',
                'language' => 'th',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 128,
                'param' => 'Contact_Title_Phone',
                'title' => 'Phone:',
                'language' => 'en',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 129,
                'param' => 'Contact_Title_Phone',
                'title' => 'هاتف:',
                'language' => 'ar',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 130,
                'param' => 'Contact_Title_Phone',
                'title' => 'ข้อความ:',
                'language' => 'th',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 131,
                'param' => 'Contact_Title_Phone',
                'title' => 'Message:',
                'language' => 'en',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 132,
                'param' => 'Contact_Title_Phone',
                'title' => 'رسالة:',
                'language' => 'ar',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 133,
                'param' => 'Contact_Title_Send',
                'title' => 'ส่ง',
                'language' => 'th',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 134,
                'param' => 'Contact_Title_Send',
                'title' => 'send',
                'language' => 'en',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 135,
                'param' => 'Contact_Title_Send',
                'title' => 'يرسل',
                'language' => 'ar',
                'page_control' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
