<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class WebInfoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('web_infos')->insert([
            [
                'info_id' => 1,
                'info_type' => 1,
                'info_param' => "webname",
                'info_title' => "ชื่อเว็บไซต์ #1",
                'info_value' => '',
                'info_link' => '',
                'info_iframe' => '',
                'info_attribute' => '',
                'info_priority' => 1,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 2,
                'info_type' => 1,
                'info_param' => "companyname",
                'info_title' => "ชื่อบริษัท / ชื่อร้านค้า",
                'info_value' => '',
                'info_link' => '',
                'info_iframe' => '',
                'info_attribute' => '',
                'info_priority' => 3,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 3,
                'info_type' => 1,
                'info_param' => "image_1",
                'info_title' => "Image #1 (Logo)",
                'info_value' => '',
                'info_link' => 'upload/2025/09/09/117574030520.png',
                'info_iframe' => '',
                'info_attribute' => '',
                'info_priority' => 3,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 4,
                'info_type' => 1,
                'info_param' => "favicon",
                'info_title' => "Image favicon (Primary)",
                'info_value' => '',
                'info_link' => 'image\\logo-GGS.png 1.png',
                'info_iframe' => '',
                'info_attribute' => '',
                'info_priority' => 6,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 5,
                'info_type' => 1,
                'info_param' => "extraname",
                'info_title' => "ชื่อเว็บไซต์ #2",
                'info_value' => NULL,
                'info_link' => NULL,
                'info_iframe' => NULL,
                'info_attribute' => NULL,
                'info_priority' => 2,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 6,
                'info_type' => 1,
                'info_param' => "image_2",
                'info_title' => "Image #2 (Qrcode)",
                'info_value' => NULL,
                'info_link' => 'upload/2025/08/19/217555798770.png',
                'info_iframe' => NULL,
                'info_attribute' => NULL,
                'info_priority' => 4,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 7,
                'info_type' => 1,
                'info_param' => "image_3",
                'info_title' => "Image #3 (#1)",
                'info_value' => NULL,
                'info_link' => 'upload/2025/08/19/317555799570.png',
                'info_iframe' => NULL,
                'info_attribute' => NULL,
                'info_priority' => 4,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 8,
                'info_type' => 1,
                'info_param' => "image_4",
                'info_title' => "Image #4 (#2)",
                'info_value' => NULL,
                'info_link' => 'upload/2025/08/19/417555799570.png',
                'info_iframe' => NULL,
                'info_attribute' => NULL,
                'info_priority' => 4,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 9,
                'info_type' => 1,
                'info_param' => "image_5",
                'info_title' => "Image #5 (#3)",
                'info_value' => NULL,
                'info_link' => 'upload/2025/08/19/517555863240.png',
                'info_iframe' => NULL,
                'info_attribute' => NULL,
                'info_priority' => 4,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 1,
                'info_type' => 1,
                'info_param' => "webname",
                'info_title' => "ชื่อเว็บไซต์ #1",
                'info_value' => '',
                'info_link' => '',
                'info_iframe' => '',
                'info_attribute' => '',
                'info_priority' => 1,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 1,
                'info_type' => 1,
                'info_param' => "webname",
                'info_title' => "ชื่อเว็บไซต์ #1",
                'info_value' => '',
                'info_link' => '',
                'info_iframe' => '',
                'info_attribute' => '',
                'info_priority' => 1,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 1,
                'info_type' => 1,
                'info_param' => "webname",
                'info_title' => "ชื่อเว็บไซต์ #1",
                'info_value' => '',
                'info_link' => '',
                'info_iframe' => '',
                'info_attribute' => '',
                'info_priority' => 1,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 1,
                'info_type' => 1,
                'info_param' => "webname",
                'info_title' => "ชื่อเว็บไซต์ #1",
                'info_value' => '',
                'info_link' => '',
                'info_iframe' => '',
                'info_attribute' => '',
                'info_priority' => 1,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 1,
                'info_type' => 1,
                'info_param' => "webname",
                'info_title' => "ชื่อเว็บไซต์ #1",
                'info_value' => '',
                'info_link' => '',
                'info_iframe' => '',
                'info_attribute' => '',
                'info_priority' => 1,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 1,
                'info_type' => 1,
                'info_param' => "webname",
                'info_title' => "ชื่อเว็บไซต์ #1",
                'info_value' => '',
                'info_link' => '',
                'info_iframe' => '',
                'info_attribute' => '',
                'info_priority' => 1,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 1,
                'info_type' => 1,
                'info_param' => "webname",
                'info_title' => "ชื่อเว็บไซต์ #1",
                'info_value' => '',
                'info_link' => '',
                'info_iframe' => '',
                'info_attribute' => '',
                'info_priority' => 1,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 1,
                'info_type' => 1,
                'info_param' => "webname",
                'info_title' => "ชื่อเว็บไซต์ #1",
                'info_value' => '',
                'info_link' => '',
                'info_iframe' => '',
                'info_attribute' => '',
                'info_priority' => 1,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 1,
                'info_type' => 1,
                'info_param' => "webname",
                'info_title' => "ชื่อเว็บไซต์ #1",
                'info_value' => '',
                'info_link' => '',
                'info_iframe' => '',
                'info_attribute' => '',
                'info_priority' => 1,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 1,
                'info_type' => 1,
                'info_param' => "webname",
                'info_title' => "ชื่อเว็บไซต์ #1",
                'info_value' => '',
                'info_link' => '',
                'info_iframe' => '',
                'info_attribute' => '',
                'info_priority' => 1,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 1,
                'info_type' => 1,
                'info_param' => "webname",
                'info_title' => "ชื่อเว็บไซต์ #1",
                'info_value' => '',
                'info_link' => '',
                'info_iframe' => '',
                'info_attribute' => '',
                'info_priority' => 1,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 1,
                'info_type' => 1,
                'info_param' => "webname",
                'info_title' => "ชื่อเว็บไซต์ #1",
                'info_value' => '',
                'info_link' => '',
                'info_iframe' => '',
                'info_attribute' => '',
                'info_priority' => 1,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'info_id' => 1,
                'info_type' => 1,
                'info_param' => "webname",
                'info_title' => "ชื่อเว็บไซต์ #1",
                'info_value' => '',
                'info_link' => '',
                'info_iframe' => '',
                'info_attribute' => '',
                'info_priority' => 1,
                'info_display' =>1,
                'admin_level' => 3,
                'language' => "th",
                'defaults' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
        ]);
    }
}
